### ISSUE TITLE
Unity is unable to resolve packages from manifest file

### ISSUE THREAD

**Issue by jajanpreet** [intelligide/assimp-unity#11]
Hi I am trying to integrate this library into my Unity project but I get the following error

An error occurred while resolving packages:
  Project has invalid dependencies:
    com.frozenstorminteractive.assimp: Package [com.frozenstorminteractive.assimp@4.1.0] cannot be found
    com.frozenstorminteractive.assimp.linux: Package [com.frozenstorminteractive.assimp.linux@4.1.0] cannot be found
    com.frozenstorminteractive.assimp.windows: Package [com.frozenstorminteractive.assimp.windows@4.1.0] cannot be found

**Comment by intelligide** [comment]
I was a little too fast on the documentation, version 4.1.0 is not yet available in stable version. But it is possible to use the preview 1 (it should work on Windows, Linux and Android, I will soon test on Mac and iOS.):
```
"dependencies": {
  ...
  "com.frozenstorminteractive.assimp": "4.1.0-pre.1",
  "com.frozenstorminteractive.assimp.windows": "4.1.0-pre.1",
  "com.frozenstorminteractive.assimp.linux": "4.1.0-pre.1",
}
...
```

**Comment by jajanpreet** [comment]
Thanks for your response. Solved my problem
