### ISSUE TITLE
Documentation help

### ISSUE THREAD

**Issue by jajanpreet** [intelligide/assimp-unity#12]
Hi I am trying to make a unity game object out of the imported asset "Scene" from library. I have no leads on how to get a Unity game object from the imported file. Can you please point me to the right documentation

**Comment by intelligide** [comment]
There is nothing to import a scene into a UNity object and I don't plan to add one. It's a low level library that just allows you to read meshes from a file format, you have to transpose this data by your own means.

Unity has made a small documentation to create procedural meshes: https://docs.unity3d.com/Manual/GeneratingMeshGeometryProcedurally.html
You can also use the test project as an example, there is a script I use to test that the library works well: https://github.com/intelligide/assimp-unity/blob/master/TestProjects/Assimp_URP_Tests/Assets/Scripts/LoadAssimpScene.cs

**Comment by intelligide** [comment]
I have not written any such tutorials. Maybe there are some on the Internet.
